Update build-and-commit-sh.yml

diff --git a/.github/workflows/build-and-commit-sh.yml b/.github/workflows/build-and-commit-sh.yml
--- a/.github/workflows/build-and-commit-sh.yml
+++ b/.github/workflows/build-and-commit-sh.yml
@@ -52,11 +52,51 @@ jobs:
             echo ">>>>>> Running test.sh <<<<<<<"
             sh test.sh
           fi
+        env:
+          is_os_darwin_mac: 0
+          is_os_window: 0
+          is_os_wsl: 0
+          is_os_ubuntu: 1
+          is_os_chromeos: 0
+          is_os_mingw64: 0
+          is_os_android_termux: 0
+
+      - name: Format Plain Text and JS
+        continue-on-error: true
+        run: |
+          echo '>> Formatting Plain Text (md txt sh ps1 config...)'
           
-          if [ -f format.sh ]; then
-            echo ">>>>>> Running format.sh <<<<<<<"
-            sh format.sh
-          fi
+          # Define patterns
+          PATTERNS=(
+            "*.md"
+            "*.txt"
+            "*.sh"
+            "*.ps1"
+            "*.config"
+            ".gitignore"
+            ".prettierignore"
+          )
+
+          # Build the find arguments
+          name_args=()
+          for i in "${!PATTERNS[@]}"; do
+              name_args+=("-name" "${PATTERNS[$i]}")
+              if [ $i -lt $((${#PATTERNS[@]} - 1)) ]; then
+                  name_args+=("-o")
+              fi
+          done
+
+          # Find and trim trailing whitespace
+          find . -type d \( -path "./node_modules" -o -name ".git" \) -prune -o -type f \( "${name_args[@]}" \) -print | while read -r file; do
+              echo "$(readlink -f "$file")"
+              sed -i 's/[ \t]*$//' "$file"
+          done
+          
+          echo '>> DONE Formatting Plain Text (md txt sh ps1 config...)'
+
+          echo '>> Formatting JS Scripts'
+          npm run format || echo "npm format failed but continuing..."
+          echo '>> DONE Formatting JS Scripts'
         env:
           is_os_darwin_mac: 0
           is_os_window: 0
